### ISSUE TITLE
[Bugfix] - Zero prefix

### ISSUE THREAD

**Issue by Sammi89** [brick/phonenumber#12] opened 2020-10-05 08:01 UTC
Hi guys
There is a **particularly problematic bug** in the parse functionality.
The function remove the zero numbers from the prefix.
`Eg: 00391234567 --> 391234567`
This is not a good behavior because in some countries the zero numbers in prefix are integral part of the phone number.
There is a way to fix this?

Thanks

**Comment by BenMorel** [comment] 2020-10-05 08:37
Hi, can you please provide the full code sample and expected output?

**Comment by Sammi89** [comment] 2020-10-16 09:44
Hi, this is my code.
```php
use Brick\PhoneNumber\PhoneNumber;
use Brick\PhoneNumber\PhoneNumberParseException;

[...]

try {
    if (starts_with($phone, '+')) {
        $number = PhoneNumber::parse($phone);
    }
    else {
        $number = PhoneNumber::parse($phone, 'IT');
    }

    $phone = $number->getNationalNumber();
}
catch (PhoneNumberParseException $e) {
    [...]
}
```
The `$phone` variable assume the following values:

- Input: `$phone = "+390116511111"`
- Output: `$phone === "116511111"` instead of `$phone === "0116511111"`

Thank you for help.

**Comment by BenMorel** [comment] 2020-10-16 12:07
Hi, `getNationalNumber()`, by design, returns the un-prefixed number, without +CountryCode and without leading zero.

What you're looking for is probably `formatForCallingFrom()`:

```php
echo $number->getCountryCode(); // 39
echo $number->getNationalNumber(); // 116511111
echo $number->formatForCallingFrom('IT'); // 011 651 1111
```

---

By the way, you don't need to check if `$phone` starts with `+`, you can always parse with a country code, it will be ignored if the phone number starts with `+`.

I'm closing this, please comment if I missed something!

**Closed as completed by BenMorel** 2020-10-16 12:07 UTC
